// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI1990081;

#nullable disable

namespace WebAPI1990081.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220214194016_Plataforma")]
    partial class Plataforma
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAPI1990081.Entidades.Juego", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("WebAPI1990081.Entidades.Plataforma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("compania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("juegoid")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("juegoid");

                    b.ToTable("Plataforma");
                });

            modelBuilder.Entity("WebAPI1990081.Entidades.Plataforma", b =>
                {
                    b.HasOne("WebAPI1990081.Entidades.Juego", "juego")
                        .WithMany("plataformas")
                        .HasForeignKey("juegoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("juego");
                });

            modelBuilder.Entity("WebAPI1990081.Entidades.Juego", b =>
                {
                    b.Navigation("plataformas");
                });
#pragma warning restore 612, 618
        }
    }
}
